/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PropostaTokenRouteImport } from './routes/proposta.$token'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as FinancialInvoicesRouteImport } from './routes/financial/invoices'
import { Route as FinancialDashboardRouteImport } from './routes/financial/dashboard'
import { Route as DmeTokenRouteImport } from './routes/dme.$token'
import { Route as ApproveTokenRouteImport } from './routes/approve.$token'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedParceirosRouteImport } from './routes/_authenticated/parceiros'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicFaviconRouteImport } from './routes/api/public/favicon'
import { Route as AuthenticatedPropostasProposalIdRouteImport } from './routes/_authenticated/propostas.$proposalId'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos.$projectId'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes.$clientId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPropostaTokenRouteImport } from './routes/api/public/proposta.$token'
import { Route as ApiPublicProposalTokenRouteImport } from './routes/api/public/proposal.$token'
import { Route as ApiPublicHooksDispatchPushRouteImport } from './routes/api/public/hooks/dispatch-push'
import { Route as ApiPublicDmeTokenRouteImport } from './routes/api/public/dme.$token'
import { Route as ApiPublicApproveTokenRouteImport } from './routes/api/public/approve.$token'

const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropostaTokenRoute = PropostaTokenRouteImport.update({
  id: '/proposta/$token',
  path: '/proposta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialInvoicesRoute = FinancialInvoicesRouteImport.update({
  id: '/financial/invoices',
  path: '/financial/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialDashboardRoute = FinancialDashboardRouteImport.update({
  id: '/financial/dashboard',
  path: '/financial/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DmeTokenRoute = DmeTokenRouteImport.update({
  id: '/dme/$token',
  path: '/dme/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParceirosRoute = AuthenticatedParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFaviconRoute = ApiPublicFaviconRouteImport.update({
  id: '/api/public/favicon',
  path: '/api/public/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropostasProposalIdRoute =
  AuthenticatedPropostasProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => AuthenticatedPropostasRoute,
  } as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropostaTokenRoute = ApiPublicPropostaTokenRouteImport.update({
  id: '/api/public/proposta/$token',
  path: '/api/public/proposta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProposalTokenRoute = ApiPublicProposalTokenRouteImport.update({
  id: '/api/public/proposal/$token',
  path: '/api/public/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDispatchPushRoute =
  ApiPublicHooksDispatchPushRouteImport.update({
    id: '/api/public/hooks/dispatch-push',
    path: '/api/public/hooks/dispatch-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDmeTokenRoute = ApiPublicDmeTokenRouteImport.update({
  id: '/api/public/dme/$token',
  path: '/api/public/dme/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApproveTokenRoute = ApiPublicApproveTokenRouteImport.update({
  id: '/api/public/approve/$token',
  path: '/api/public/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/parceiros': typeof AuthenticatedParceirosRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/dme/$token': typeof DmeTokenRoute
  '/financial/dashboard': typeof FinancialDashboardRoute
  '/financial/invoices': typeof FinancialInvoicesRoute
  '/p/$token': typeof PTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
  '/api/public/favicon': typeof ApiPublicFaviconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/approve/$token': typeof ApiPublicApproveTokenRoute
  '/api/public/dme/$token': typeof ApiPublicDmeTokenRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/proposal/$token': typeof ApiPublicProposalTokenRoute
  '/api/public/proposta/$token': typeof ApiPublicPropostaTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/parceiros': typeof AuthenticatedParceirosRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/dme/$token': typeof DmeTokenRoute
  '/financial/dashboard': typeof FinancialDashboardRoute
  '/financial/invoices': typeof FinancialInvoicesRoute
  '/p/$token': typeof PTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
  '/api/public/favicon': typeof ApiPublicFaviconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/approve/$token': typeof ApiPublicApproveTokenRoute
  '/api/public/dme/$token': typeof ApiPublicDmeTokenRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/proposal/$token': typeof ApiPublicProposalTokenRoute
  '/api/public/proposta/$token': typeof ApiPublicPropostaTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/parceiros': typeof AuthenticatedParceirosRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/_authenticated/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/dme/$token': typeof DmeTokenRoute
  '/financial/dashboard': typeof FinancialDashboardRoute
  '/financial/invoices': typeof FinancialInvoicesRoute
  '/p/$token': typeof PTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/_authenticated/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/_authenticated/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
  '/api/public/favicon': typeof ApiPublicFaviconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/approve/$token': typeof ApiPublicApproveTokenRoute
  '/api/public/dme/$token': typeof ApiPublicDmeTokenRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/proposal/$token': typeof ApiPublicProposalTokenRoute
  '/api/public/proposta/$token': typeof ApiPublicPropostaTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/convite'
    | '/aprovacoes'
    | '/calendario'
    | '/ceo'
    | '/clientes'
    | '/config'
    | '/crm'
    | '/dashboard'
    | '/financeiro'
    | '/integracoes'
    | '/jobs'
    | '/metas'
    | '/noticias'
    | '/parceiros'
    | '/portal'
    | '/projetos'
    | '/propostas'
    | '/relatorios'
    | '/approve/$token'
    | '/dme/$token'
    | '/financial/dashboard'
    | '/financial/invoices'
    | '/p/$token'
    | '/proposal/$token'
    | '/proposta/$token'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/propostas/$proposalId'
    | '/api/public/favicon'
    | '/api/public/manifest'
    | '/api/public/approve/$token'
    | '/api/public/dme/$token'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/proposal/$token'
    | '/api/public/proposta/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/convite'
    | '/aprovacoes'
    | '/calendario'
    | '/ceo'
    | '/clientes'
    | '/config'
    | '/crm'
    | '/dashboard'
    | '/financeiro'
    | '/integracoes'
    | '/jobs'
    | '/metas'
    | '/noticias'
    | '/parceiros'
    | '/portal'
    | '/projetos'
    | '/propostas'
    | '/relatorios'
    | '/approve/$token'
    | '/dme/$token'
    | '/financial/dashboard'
    | '/financial/invoices'
    | '/p/$token'
    | '/proposal/$token'
    | '/proposta/$token'
    | '/'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/propostas/$proposalId'
    | '/api/public/favicon'
    | '/api/public/manifest'
    | '/api/public/approve/$token'
    | '/api/public/dme/$token'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/proposal/$token'
    | '/api/public/proposta/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/convite'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/calendario'
    | '/_authenticated/ceo'
    | '/_authenticated/clientes'
    | '/_authenticated/config'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/integracoes'
    | '/_authenticated/jobs'
    | '/_authenticated/metas'
    | '/_authenticated/noticias'
    | '/_authenticated/parceiros'
    | '/_authenticated/portal'
    | '/_authenticated/projetos'
    | '/_authenticated/propostas'
    | '/_authenticated/relatorios'
    | '/approve/$token'
    | '/dme/$token'
    | '/financial/dashboard'
    | '/financial/invoices'
    | '/p/$token'
    | '/proposal/$token'
    | '/proposta/$token'
    | '/_authenticated/'
    | '/_authenticated/clientes/$clientId'
    | '/_authenticated/projetos/$projectId'
    | '/_authenticated/propostas/$proposalId'
    | '/api/public/favicon'
    | '/api/public/manifest'
    | '/api/public/approve/$token'
    | '/api/public/dme/$token'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/proposal/$token'
    | '/api/public/proposta/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteRoute: typeof ConviteRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  DmeTokenRoute: typeof DmeTokenRoute
  FinancialDashboardRoute: typeof FinancialDashboardRoute
  FinancialInvoicesRoute: typeof FinancialInvoicesRoute
  PTokenRoute: typeof PTokenRoute
  ProposalTokenRoute: typeof ProposalTokenRoute
  PropostaTokenRoute: typeof PropostaTokenRoute
  ApiPublicFaviconRoute: typeof ApiPublicFaviconRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicApproveTokenRoute: typeof ApiPublicApproveTokenRoute
  ApiPublicDmeTokenRoute: typeof ApiPublicDmeTokenRoute
  ApiPublicHooksDispatchPushRoute: typeof ApiPublicHooksDispatchPushRoute
  ApiPublicProposalTokenRoute: typeof ApiPublicProposalTokenRoute
  ApiPublicPropostaTokenRoute: typeof ApiPublicPropostaTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/proposta/$token': {
      id: '/proposta/$token'
      path: '/proposta/$token'
      fullPath: '/proposta/$token'
      preLoaderRoute: typeof PropostaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial/invoices': {
      id: '/financial/invoices'
      path: '/financial/invoices'
      fullPath: '/financial/invoices'
      preLoaderRoute: typeof FinancialInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial/dashboard': {
      id: '/financial/dashboard'
      path: '/financial/dashboard'
      fullPath: '/financial/dashboard'
      preLoaderRoute: typeof FinancialDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dme/$token': {
      id: '/dme/$token'
      path: '/dme/$token'
      fullPath: '/dme/$token'
      preLoaderRoute: typeof DmeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros': {
      id: '/_authenticated/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof AuthenticatedParceirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/favicon': {
      id: '/api/public/favicon'
      path: '/api/public/favicon'
      fullPath: '/api/public/favicon'
      preLoaderRoute: typeof ApiPublicFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/propostas/$proposalId': {
      id: '/_authenticated/propostas/$proposalId'
      path: '/$proposalId'
      fullPath: '/propostas/$proposalId'
      preLoaderRoute: typeof AuthenticatedPropostasProposalIdRouteImport
      parentRoute: typeof AuthenticatedPropostasRoute
    }
    '/_authenticated/projetos/$projectId': {
      id: '/_authenticated/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/clientes/$clientId': {
      id: '/_authenticated/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposta/$token': {
      id: '/api/public/proposta/$token'
      path: '/api/public/proposta/$token'
      fullPath: '/api/public/proposta/$token'
      preLoaderRoute: typeof ApiPublicPropostaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proposal/$token': {
      id: '/api/public/proposal/$token'
      path: '/api/public/proposal/$token'
      fullPath: '/api/public/proposal/$token'
      preLoaderRoute: typeof ApiPublicProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-push': {
      id: '/api/public/hooks/dispatch-push'
      path: '/api/public/hooks/dispatch-push'
      fullPath: '/api/public/hooks/dispatch-push'
      preLoaderRoute: typeof ApiPublicHooksDispatchPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dme/$token': {
      id: '/api/public/dme/$token'
      path: '/api/public/dme/$token'
      fullPath: '/api/public/dme/$token'
      preLoaderRoute: typeof ApiPublicDmeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve/$token': {
      id: '/api/public/approve/$token'
      path: '/api/public/approve/$token'
      fullPath: '/api/public/approve/$token'
      preLoaderRoute: typeof ApiPublicApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedProjetosRouteChildren {
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRoute
}

const AuthenticatedProjetosRouteChildren: AuthenticatedProjetosRouteChildren = {
  AuthenticatedProjetosProjectIdRoute: AuthenticatedProjetosProjectIdRoute,
}

const AuthenticatedProjetosRouteWithChildren =
  AuthenticatedProjetosRoute._addFileChildren(
    AuthenticatedProjetosRouteChildren,
  )

interface AuthenticatedPropostasRouteChildren {
  AuthenticatedPropostasProposalIdRoute: typeof AuthenticatedPropostasProposalIdRoute
}

const AuthenticatedPropostasRouteChildren: AuthenticatedPropostasRouteChildren =
  {
    AuthenticatedPropostasProposalIdRoute:
      AuthenticatedPropostasProposalIdRoute,
  }

const AuthenticatedPropostasRouteWithChildren =
  AuthenticatedPropostasRoute._addFileChildren(
    AuthenticatedPropostasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedParceirosRoute: typeof AuthenticatedParceirosRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRouteWithChildren
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedParceirosRoute: AuthenticatedParceirosRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRouteWithChildren,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteRoute: ConviteRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  DmeTokenRoute: DmeTokenRoute,
  FinancialDashboardRoute: FinancialDashboardRoute,
  FinancialInvoicesRoute: FinancialInvoicesRoute,
  PTokenRoute: PTokenRoute,
  ProposalTokenRoute: ProposalTokenRoute,
  PropostaTokenRoute: PropostaTokenRoute,
  ApiPublicFaviconRoute: ApiPublicFaviconRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicApproveTokenRoute: ApiPublicApproveTokenRoute,
  ApiPublicDmeTokenRoute: ApiPublicDmeTokenRoute,
  ApiPublicHooksDispatchPushRoute: ApiPublicHooksDispatchPushRoute,
  ApiPublicProposalTokenRoute: ApiPublicProposalTokenRoute,
  ApiPublicPropostaTokenRoute: ApiPublicPropostaTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
