/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedPropostasProposalIdRouteImport } from './routes/_authenticated/propostas.$proposalId'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos.$projectId'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes.$clientId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasProposalIdRoute =
  AuthenticatedPropostasProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => AuthenticatedPropostasRoute,
  } as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ceo': typeof AuthenticatedCeoRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/_authenticated/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/_authenticated/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRoute
  '/_authenticated/propostas/$proposalId': typeof AuthenticatedPropostasProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ceo'
    | '/clientes'
    | '/config'
    | '/crm'
    | '/equipe'
    | '/financeiro'
    | '/jobs'
    | '/portal'
    | '/projetos'
    | '/propostas'
    | '/relatorios'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/propostas/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ceo'
    | '/clientes'
    | '/config'
    | '/crm'
    | '/equipe'
    | '/financeiro'
    | '/jobs'
    | '/portal'
    | '/projetos'
    | '/propostas'
    | '/relatorios'
    | '/'
    | '/clientes/$clientId'
    | '/projetos/$projectId'
    | '/propostas/$proposalId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ceo'
    | '/_authenticated/clientes'
    | '/_authenticated/config'
    | '/_authenticated/crm'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/jobs'
    | '/_authenticated/portal'
    | '/_authenticated/projetos'
    | '/_authenticated/propostas'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
    | '/_authenticated/clientes/$clientId'
    | '/_authenticated/projetos/$projectId'
    | '/_authenticated/propostas/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas/$proposalId': {
      id: '/_authenticated/propostas/$proposalId'
      path: '/$proposalId'
      fullPath: '/propostas/$proposalId'
      preLoaderRoute: typeof AuthenticatedPropostasProposalIdRouteImport
      parentRoute: typeof AuthenticatedPropostasRoute
    }
    '/_authenticated/projetos/$projectId': {
      id: '/_authenticated/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/clientes/$clientId': {
      id: '/_authenticated/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedProjetosRouteChildren {
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRoute
}

const AuthenticatedProjetosRouteChildren: AuthenticatedProjetosRouteChildren = {
  AuthenticatedProjetosProjectIdRoute: AuthenticatedProjetosProjectIdRoute,
}

const AuthenticatedProjetosRouteWithChildren =
  AuthenticatedProjetosRoute._addFileChildren(
    AuthenticatedProjetosRouteChildren,
  )

interface AuthenticatedPropostasRouteChildren {
  AuthenticatedPropostasProposalIdRoute: typeof AuthenticatedPropostasProposalIdRoute
}

const AuthenticatedPropostasRouteChildren: AuthenticatedPropostasRouteChildren =
  {
    AuthenticatedPropostasProposalIdRoute:
      AuthenticatedPropostasProposalIdRoute,
  }

const AuthenticatedPropostasRouteWithChildren =
  AuthenticatedPropostasRoute._addFileChildren(
    AuthenticatedPropostasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRouteWithChildren
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCeoRoute: AuthenticatedCeoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRouteWithChildren,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
